### ISSUE TITLE
Erro artifactory.docker 

### ISSUE THREAD

**Issue by asoubeck** [pasknel/epyon#1]
E ae jovem, tem que adicionar no config-examples.yaml a informação do docker { docker: "artifactory.docker" }, se não retorna o seguinte erro:

FATA[0000] empty config parameter: artifactory.docker 

Atualmente está assim:

artifactory:
  repositories: "./artifactory/repositories"
  workers: 10

Para funcionar tem que estar assim:

artifactory:
  repositories: "./artifactory/repositories"
  docker: "artifactory.docker"
  workers: 10

Abraços...

**Comment by pasknel** [comment]
Correções do config-examples.yaml feitas no ultimo commit.
